services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: localizei_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 30s

volumes:
  pg_data:
